name: todo
description: To do app with bloc and hive
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0-69.2.beta <3.0.0"

dependencies:
  flutter_bloc:
  equatable:
  hive:
  hive_flutter:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  build_runner:
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true